#!/usr/bin/env bash
# scripts/sync-standards.sh
# Factoría Standards — propagate templates and the constitution block to a
# target project repo.
#
# What it syncs and where:
#   AGENTS.md                      → <repo>/AGENTS.md   (ONLY the block between markers)
#   templates/CLAUDE.md            → <repo>/CLAUDE.md
#   templates/gemini-settings.json → <repo>/.gemini/settings.json
#   templates/CODEOWNERS           → <repo>/.github/CODEOWNERS
#   templates/pull_request_template.md → <repo>/.github/pull_request_template.md
#   templates/ISSUE_TEMPLATE/*     → <repo>/.github/ISSUE_TEMPLATE/
#
# What it deliberately does NOT sync:
#   ci/*.yml       — consumed by reference (workflow_call), never copied.
#   validators/*   — consumed by reference (checked out by db-gate), never copied.
#   eslint-config/ — consumed as npm dependency, never copied.
#
# Usage:
#   ./scripts/sync-standards.sh <path-to-target-repo> [--check] [--yes]
#     --check  report drift only, change nothing, exit 1 if drift found
#     --yes    apply without interactive confirmation (for scripting)
#
# The AGENTS.md block is stamped with the standards version (git tag/sha)
# so any repo can answer "which version of the law am I on?"

set -euo pipefail

STANDARDS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="${1:?Usage: sync-standards.sh <path-to-target-repo> [--check] [--yes]}"
MODE_CHECK=false
MODE_YES=false
[[ "${2:-}" == "--check" || "${3:-}" == "--check" ]] && MODE_CHECK=true
[[ "${2:-}" == "--yes"   || "${3:-}" == "--yes"   ]] && MODE_YES=true

if [ ! -d "$TARGET" ]; then
  echo "::error::Target repo path '$TARGET' does not exist." && exit 1
fi

VERSION=$(git -C "$STANDARDS_ROOT" describe --tags --always 2>/dev/null || echo "unknown")
DRIFT=0
CHANGED=0

BEGIN_MARK="<!-- FACTORIA:BEGIN (autogenerated — do not edit between markers; run sync-standards.sh) -->"
END_MARK="<!-- FACTORIA:END -->"

confirm() {
  $MODE_YES && return 0
  read -r -p "$1 [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}

# ---------------------------------------------------------------
# Plain-copy files: report diff, confirm, copy
# ---------------------------------------------------------------
sync_file() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"

  if [ -f "$dst" ] && diff -q "$src" "$dst" >/dev/null 2>&1; then
    echo "  ok        $(basename "$dst")"
    return 0
  fi

  DRIFT=$((DRIFT + 1))
  if $MODE_CHECK; then
    echo "  DRIFT     $dst differs from standards"
    return 0
  fi

  if [ -f "$dst" ]; then
    echo "  differs   $dst"
    diff -u "$dst" "$src" | head -40 || true
    if confirm "  Overwrite $dst with standards version?"; then
      cp "$src" "$dst"; CHANGED=$((CHANGED + 1)); echo "  updated   $dst"
    else
      echo "  skipped   $dst (kept local version — verify this is intentional)"
    fi
  else
    cp "$src" "$dst"; CHANGED=$((CHANGED + 1)); echo "  created   $dst"
  fi
}

echo "Syncing factoria-standards@$VERSION → $TARGET"
echo ""
echo "── Plain-copy templates ──"
sync_file "$STANDARDS_ROOT/templates/CLAUDE.md"                    "$TARGET/CLAUDE.md"
sync_file "$STANDARDS_ROOT/templates/gemini-settings.json"         "$TARGET/.gemini/settings.json"
sync_file "$STANDARDS_ROOT/templates/CODEOWNERS"                   "$TARGET/.github/CODEOWNERS"
sync_file "$STANDARDS_ROOT/templates/pull_request_template.md"     "$TARGET/.github/pull_request_template.md"
for t in "$STANDARDS_ROOT"/templates/ISSUE_TEMPLATE/*.yml; do
  sync_file "$t" "$TARGET/.github/ISSUE_TEMPLATE/$(basename "$t")"
done

# ---------------------------------------------------------------
# AGENTS.md: replace ONLY the marked block, preserve the rest
# ---------------------------------------------------------------
echo ""
echo "── AGENTS.md (marked block) ──"

SRC_AGENTS="$STANDARDS_ROOT/AGENTS.md"
DST_AGENTS="$TARGET/AGENTS.md"

NEW_BLOCK="$BEGIN_MARK
<!-- factoria-standards version: $VERSION -->
$(cat "$SRC_AGENTS")
$END_MARK"

if [ ! -f "$DST_AGENTS" ]; then
  if $MODE_CHECK; then
    echo "  DRIFT     AGENTS.md missing in target"; DRIFT=$((DRIFT + 1))
  else
    printf '%s\n\n## Project-specific rules\n<!-- Tech/template rules below. May ADD rules, MUST NOT override [HARD]. -->\n' "$NEW_BLOCK" > "$DST_AGENTS"
    CHANGED=$((CHANGED + 1)); echo "  created   AGENTS.md (with empty project section)"
  fi
elif grep -qF "$BEGIN_MARK" "$DST_AGENTS" && grep -qF "$END_MARK" "$DST_AGENTS"; then
  # Extract current block and compare
  CURRENT_BLOCK=$(awk "/^$(printf '%s' "$BEGIN_MARK" | sed 's/[][\.*^$()+?{}|/]/\\&/g')\$/,/^$(printf '%s' "$END_MARK" | sed 's/[][\.*^$()+?{}|/]/\\&/g')\$/" "$DST_AGENTS")
  if [ "$CURRENT_BLOCK" == "$NEW_BLOCK" ]; then
    echo "  ok        AGENTS.md block up to date"
  else
    DRIFT=$((DRIFT + 1))
    if $MODE_CHECK; then
      echo "  DRIFT     AGENTS.md block outdated (standards changed since last sync)"
    elif confirm "  Update the standards block in AGENTS.md (project section untouched)?"; then
      TMP=$(mktemp)
      awk -v begin="$BEGIN_MARK" -v end="$END_MARK" -v block="$NEW_BLOCK" '
        $0 == begin {inblock=1; print block; next}
        $0 == end   {inblock=0; next}
        !inblock    {print}
      ' "$DST_AGENTS" > "$TMP" && mv "$TMP" "$DST_AGENTS"
      CHANGED=$((CHANGED + 1)); echo "  updated   AGENTS.md block → $VERSION"
    fi
  fi
else
  DRIFT=$((DRIFT + 1))
  echo "  WARNING   AGENTS.md exists but has NO factoria markers."
  echo "            Cannot sync safely — add markers manually around the"
  echo "            standards block, or recreate from template. Not touching it."
fi

# ---------------------------------------------------------------
# Summary
# ---------------------------------------------------------------
echo ""
if $MODE_CHECK; then
  if [ "$DRIFT" -gt 0 ]; then
    echo "::error::CHECK FAILED: $DRIFT file(s) drifted from standards@$VERSION."
    exit 1
  fi
  echo "CHECK PASSED: target is in sync with standards@$VERSION."
else
  echo "Done: $CHANGED file(s) changed, $DRIFT drift(s) found."
  [ "$CHANGED" -gt 0 ] && echo "Review with 'git diff' in the target repo and commit via PR (Human Gate: standards files)."
fi